### ISSUE TITLE
Incorrect Server Name in Service Monitor of Volume Expander Operator

### ISSUE THREAD

**Issue by Muneebstakater** [redhat-cop/volume-expander-operator#22]
I am trying to launch volume expander operator on openshift 4.8.28 from the command line with the below command.
oc new-project stakater-volume-expander-operator
oc apply -f config/operatorhub -n stakater-volume-expander-operator

The above command creates csv, operator group, pods, service, service monitor etc. But the created service monitor reflects incorrect server name due to which prometheus unable to populate metrices with the error "x509 certificate is valid for   "volume-expander-operator-controller-manager-metrics.stakater-volume-expander-operator.svc" not valid for "volume-expander-operator-controller-manager-metrics.volume-expander-operator.svc". Below is the servicemonitor created after launching the operator.
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2022-02-07T09:07:30Z"
  generation: 1
  labels:
    operator: volume-expander-operator
  name: volume-expander-operator-controller-manager-metrics-monitor
  namespace: stakater-volume-expander-operator
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: volume-expander-operator.v0.3.2
    uid: ca3e47f1-807d-4872-9be8-915a1f8e7375
  resourceVersion: "64293388"
  uid: 08891dee-fbeb-48a3-88a6-171962dfeed7
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: volume-expander-operator-controller-manager-metrics.volume-expander-operator.svc
  selector:
    matchLabels:
      operator: volume-expander-operator
```                                      

Below is the servername created after installing the operator 
serverName: volume-expander-operator-controller-manager-metrics.volume-expander-operator.svc

However the serverName in servicemonitor should be `volume-expander-operator-controller-manager-metrics.stakater-volume-expander-operator.svc` so that prometheus will populate the metrices.

**Comment by Muneebstakater** [comment]
This is still not fixed and we are receiving below error on prometheus:

`Get "https://10.131.1.237:8443/metrics": x509: certificate is valid for volume-expander-operator-controller-manager-metrics.stakater-volume-expander-operator.svc, volume-expander-operator-controller-manager-metrics.stakater-volume-expander-operator.svc.cluster.local, not volume-expander-operator-controller-manager-metrics.volume-expander-operator.svc`

We are launching volume-expander-operator in stakater-volume-expander-operator namespace but the server name in the service monitor still reflecting incorrect  namespace `serverName: volume-expander-operator-controller-manager-metrics.volume-expander-operator.svc` instead of 'volume-expander-operator-controller-manager-metrics.stakater-volume-expander-operator.svc' or  '$(METRICS_SERVICE_NAME).$(METRICS_SERVICE_NAMESPACE).svc'

**Comment by raffaelespazzoli** [comment]
see also: https://github.com/operator-framework/operator-lifecycle-manager/issues/2619
