### ISSUE TITLE
JSON Logging for volume-expander-operator

### ISSUE THREAD

**Issue by Muneebstakater** [redhat-cop/volume-expander-operator#23]
We have installed the volume expander operator but the logging format is not in JSON and for troubleshooting purposes logging should be in standard JSON format. Below are the sample logs generated for volume expander operator.

2022-02-07T11:42:51.284Z	INFO	controller-runtime.manager.controller.persistentvolumeclaim	Starting workers	{"reconciler group": "", "reconciler kind": "PersistentVolumeClaim", "worker count": 1}

**Comment by raffaelespazzoli** [comment]
I don't fully understand this question. I'm using the standard logging provided API by operator-sdk. So, perhaps you could ask there if there is a setting to turn on the json formattes?

**Comment by Muneebstakater** [comment]
In the main.go file of volume-expander-operator `zap.UseDevMode(true)` is set in `ctrl.SetLogger(zap.New(zap.UseDevMode(true)))`. Can we set somehow  this parameter from Dev to Production mode because as per the link https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/ Production Mode defaults(encoder=json) . Its easier for Openshift elasticsearch operator to parse logs in JSON so we should have a flag to toggle between default and JSON.
