### ISSUE TITLE
Auto expansion worked earlier then facing error "volume-expander-operator unexpected value"

### ISSUE THREAD

**Issue by fayazahamedj** [redhat-cop/volume-expander-operator#26]
Hi Team,

We are trying autoexpansion feature in our openshift environment through volume expander operator & we were getting error like 
below for some of the PVCs . Yesterday expansion worked fine for one of the PVC we created but today we are getting this error & also expansion didn't take place automatically for quite some time. Later, the expansion happened automatically but the "unexpected error" event is also getting repeated. 

Checked the volume expander operator logs but we don't find much in the logs to look on it further. 

![image](https://user-images.githubusercontent.com/78776689/161246410-9bcda03f-d49f-4968-ada6-219cb78c9127.png)

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume-expander-operator.redhat-cop.io/autoexpand: 'true'
    volume-expander-operator.redhat-cop.io/expand-threshold-percent: '85'
    volume-expander-operator.redhat-cop.io/expand-up-to: 5Gi
    volume-expander-operator.redhat-cop.io/polling-frequency: 5m
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
  selfLink: >-
    /api/v1/namespaces/test13/persistentvolumeclaims/test1360344
  resourceVersion: '1037639301'
  name: test1360344
  uid: 93549f62-1932-48db-97e0-04dfe0a6b081
  creationTimestamp: '2022-03-31T09:09:21Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-03-31T09:09:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:pv.kubernetes.io/bind-completed': {}
            'f:pv.kubernetes.io/bound-by-controller': {}
            'f:volume.beta.kubernetes.io/storage-provisioner': {}
        'f:spec':
          'f:volumeName': {}
        'f:status':
          'f:accessModes': {}
          'f:capacity': {}
          'f:phase': {}
    - manager: okhttp
      operation: Update
      apiVersion: v1
      time: '2022-03-31T09:09:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:volume-expander-operator.redhat-cop.io/autoexpand': {}
            'f:volume-expander-operator.redhat-cop.io/expand-up-to': {}
            'f:volume-expander-operator.redhat-cop.io/polling-frequency': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests': {}
          'f:storageClassName': {}
          'f:volumeMode': {}
    - manager: csi-resizer
      operation: Update
      apiVersion: v1
      time: '2022-03-31T09:14:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:capacity':
            'f:storage': {}
    - manager: manager
      operation: Update
      apiVersion: v1
      time: '2022-03-31T09:14:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:resources':
            'f:requests':
              'f:storage': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-04-01T08:18:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:volume-expander-operator.redhat-cop.io/expand-threshold-percent': {}
  namespace: test13-intel
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2560Mi
  volumeName: pvc-93549f62-1932-48db-97e0-04dfe0a6b081
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi

Thanks,
Fayaz

**Comment by raffaelespazzoli** [comment]
so you are getting that error in the events associated to the PVC? There should be something in the pod log providing more details on the error.

**Comment by fayazahamedj** [comment]
@raffaelespazzoli , yes getting error in the events associated to that PVC. Assume you are asking the operator pod logs, sharing it below.

Observed a string "lenght":2 in lines 2 & 7, is this something causing the failure?

1. 2022-04-01T13:33:05.313Z        DEBUG   controllers.PersistentVolumeClaim       result for used bytes   {"pvc": "test/test60344", "string": "kubelet_volume_stats_used_bytes{endpoint=\"https-metrics\", instance=\"10.128.8.11:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"test\", node=\"worker601\", persistentvolumeclaim=\"test60344\", service=\"kubelet\"} => 3636461568 @[1648819985.307]\nkubelet_volume_stats_used_bytes{endpoint=\"https-metrics\", instance=\"10.128.9.139:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"test\", node=\"ceph12\", persistentvolumeclaim=\"test60344\", service=\"kubelet\"} => 3636461568 @[1648819985.307]", "type": "vector"}
2. 2022-04-01T13:33:05.313Z        ERROR   controllers.PersistentVolumeClaim       unexpected number of results    {"pvc": "test/test60344", **"lenght": 2**, "error": "unexpected value"}
3. 2022-04-01T13:33:05.313Z        ERROR   controllers.PersistentVolumeClaim       unable to poll metrics for      {"pvc": "test/test60344", "pvc": {"apiVersion": "v1", "kind": "PersistentVolumeClaim", "namespace": "test", "name": "test60344"}, "error": "unexpected value"}
4. 2022-04-01T13:33:05.313Z        ERROR   controller-runtime.manager.controller.persistentvolumeclaim     Reconciler error        {"reconciler group": "", "reconciler kind": "PersistentVolumeClaim", "name": "test60344", "namespace": "test", "error": "unexpected value"}
5. 2022-04-01T13:33:05.313Z        DEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"PersistentVolumeClaim","namespace":"test","name":"test60344","uid":"93549f62-1932-48db-97e0-04dfe0a6b081","apiVersion":"v1","resourceVersion":"1037772162"}, "reason": "UnableToExtend", "message": "unexpected value"}
6. 2022-04-01T13:34:27.240Z        DEBUG   controllers.PersistentVolumeClaim       result for used bytes   {"pvc": "test/test60344", "string": "kubelet_volume_stats_used_bytes{endpoint=\"https-metrics\", instance=\"10.128.8.11:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"test\", node=\"worker601\", persistentvolumeclaim=\"test60344\", service=\"kubelet\"} => 4294967296 @[1648820067.234]\nkubelet_volume_stats_used_bytes{endpoint=\"https-metrics\", instance=\"10.128.9.139:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"test\", node=\"ceph12\", persistentvolumeclaim=\"test60344\", service=\"kubelet\"} => 4294967296 @[1648820067.234]", "type": "vector"}
7. 2022-04-01T13:34:27.240Z        ERROR   controllers.PersistentVolumeClaim       unexpected number of results    {"pvc": "test/test60344", **"lenght": 2**, "error": "unexpected value"}
8. 2022-04-01T13:34:27.240Z        ERROR   controllers.PersistentVolumeClaim       unable to poll metrics for      {"pvc": "test/test60344", "pvc": {"apiVersion": "v1", "kind": "PersistentVolumeClaim", "namespace": "test", "name": "test60344"}, "error": "unexpected value"}
9. 2022-04-01T13:34:27.240Z        ERROR   controller-runtime.manager.controller.persistentvolumeclaim     Reconciler error        {"reconciler group": "", "reconciler kind": "PersistentVolumeClaim", "name": "test60344", "namespace": "test", "error": "unexpected value"}
10. 2022-04-01T13:34:27.240Z        DEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"PersistentVolumeClaim","namespace":"test","name":"test60344","uid":"93549f62-1932-48db-97e0-04dfe0a6b081","apiVersion":"v1","resourceVersion":"1037772162"}, "reason": "UnableToExtend", "message": "unexpected value"}

Regards,
Fayaz

**Comment by raffaelespazzoli** [comment]
I see. There's something unexpected with the metrics. This Prometheus query should return exactly one result (but it returns two in your cluster):
`kubelet_volume_stats_used_bytes{namespace="test",persistentvolumeclaim="test60344"}`
can you check and try to understand why?

**Comment by avinash-palleti** [comment]
![image](https://user-images.githubusercontent.com/362099/161518757-a1b84feb-3c76-43bf-adcd-0c1ec5a6148f.png)
We are seeing two responses in prometheus as well. Not sure why same response is coming from two nodes.

**Comment by avinash-palleti** [comment]
Looks like it is getting response from all running pods. There is possibility that 1 PVC will be used in multiple pods, so we need to change premetheus query to get unique result or an update in operator logic to handle multiple values. (All pods will anyway return same used bytes)

**Comment by avinash-palleti** [comment]
We will get an issue when there is no running pod which uses the PVC. PVC is independent of pods, so the logic should take care of all scenarios (no pods and multiple pods) to expand the storage accordingly.

**Comment by raffaelespazzoli** [comment]
`Looks like it is getting response from all running pods.` this makes sense and it's definitely a bug of this operator, it should be able to handle this situation.
`We will get an issue when there is no running pod which uses the PVC.` yes. these metrics are only exposed when the volume is mounted. I don't know how to fix this. The hope was to have CSI define these kinds of metrics, but it looks like they are not making progress in that direction.

**Comment by fayazahamedj** [comment]
@raffaelespazzoli, good to see the issue resolved.  Unfortunately don't see any operator updates as we have automatic updates in place.  

Also we see the operator version still at 0.3.4 in Marketplace. Need to wait for operator update rollout this week?

Thanks...

**Comment by davgordo** [comment]
@fayazahamedj we are targeting a release this week. We have some goals related to improving CI and we will cut a release as soon as we reach them.

**Comment by raffaelespazzoli** [comment]
@fayazahamedj we cut a new release, can  you check if it fixes the issue?
